# Generated by Django 5.1.6 on 2025-02-28 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_staffleave_approved_by_alter_staffleave_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expatdocument',
            name='document_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Work Permit', 'Work Permit'), ('Residency Permit', 'Residency Permit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expatdocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
