# Generated by Django 5.1.6 on 2025-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expatdocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_of_birth',
        ),
    ]
