# Generated by Django 5.1.6 on 2025-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_employeeprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
