# Generated by Django 5.1.6 on 2025-03-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_suppliercontract_contract_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontract',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
